apiVersion: v1
kind: Service
metadata:
  name: base-iis-server
  labels:
    app: base-iis-server
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: base-iis-server
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: base-iis-server
  name: base-iis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: base-iis-server
  template:
    metadata:
      labels:
        run: base-iis-server
        app: base-iis-server
      name: base-iis-server
    spec:
      containers:
      - name: base-iis-server
        imagePullPolicy: IfNotPresent
        image: microsoft/iis
      nodeSelector:
        beta.kubernetes.io/os: "windows"
      tolerations:
      - key: "windows"
        operator: "Exists"
        effect: "NoSchedule"
